title: Dominic Carrillo
email: DWCarrillo@outlook.com
description: >- # this means to ignore newlines until "baseurl:"
  Ph.D. student specializing in SLAM, Computer Vision, Autonomous Driving under the Connected Autonomous Vehicle lab at University of North Texas.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: CarrilloDominic
github_username: dwc13 
linkedin_username: dwc13
instagram_username: dwc_13
# discord_username: Rocket로켓#3172

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  publications:
    output: true
  blog:
    output: true
  projects:
    output: true
